baseURL = "https://syedabdulrafay.com/"
languageCode = "en-us"
title = "Abdul Rafay"
theme = "osprey-delight"

[Params]
tagline = """# A.Rafay 
Engineer. Traveller. Writer."""
enforceSinglePage = false
logoBig = "/images/logo.png"
logoSmall = "favicon.png"
favicon = "favicon.png"

[Params.Feat]
useBlog = true
lazyloading = true


## Social media links in footer:
[Params.Social]
  # [str] Link to your Twitter.
  twitter = ""
  # [str] Link to your LinkedIn.
  linkedin = ""
  # [str] Link to your Facebook.
  facebook = "https://www.facebook.com/syedabdurrafayzaidi/"
  # [str] Link to your Instagram.
  instagram = "https://www.instagram.com/abdul.rafay.zaidi/"


[[menu.main]]
  name = "About"
  url  = "/about/detail"
  weight = 1
[[menu.main]]
  name = "Stories"
  url  = "/story"
  weight = 2
[[menu.main]]
  name = "Poetry"
  url  = "/poetry"
  weight = 2
# [[menu.main]]
#   name = "Travel"
#   url  = "/#travel"
#   weight = 3
[[menu.main]]
  name = "Research"
  url  = "/research"
  weight = 3
[[menu.main]]
  name = "Blog"
  url  = "/#Blog"
  weight = 4
# [[menu.main]]
#   # Use icon here to neatly back reference an external site/blog/whatever:
#   pre = "<i class='icon icon-link-ext'></i>&nbsp;"
#   name = ""
#   url  = "/"
#   weight = 5
